spring:
  datasource:
    url: jdbc:mysql://springdb.cnf2esnbu6ka.ap-northeast-2.rds.amazonaws.com:3306/coffeebin?autoReconnect=true
    username: admin
    password: qwerty123
    driver-class-name: org.mariadb.jdbc.Driver


token:
  key: mySecret